# Generated by Django 4.2.7 on 2023-11-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file_id',
            field=models.CharField(max_length=100),
        ),
    ]
